services:
  nextjs-template:
    container_name: nextjs-template
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "3030:3030"
    volumes:
      - .:/web
    networks:
      - default-network

networks:
  default-network:
    driver: bridge
